name: build
on: [push, pull_request]
jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: make mingw-w64-x86_64-gcc
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: libpazio.a
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: libpazio.a
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: make -j
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: libpazio.a
